# This workflow will build a Java project with Maven
 
name: Java CI with Maven
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file vueblog-java/pom.xml
    - name: BuildDockerImage
      run: docker build . --file vueblog-java/Dockerfile --tag demo:$(date +%s)
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: 1301866313ding/demo:demo
        file: vueblog-java/Dockerfile
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

 
